[package]
name = "firezone-relay"
# mark:automatic-version
version = "1.0.0"
edition = "2021"

[dependencies]
secrecy = { workspace = true }
anyhow = "1.0.75"
clap = { version = "4.4.18", features = ["derive", "env"] }
bytecodec = "0.4.15"
futures = "0.3.29"
hex = "0.4.3"
hex-literal = "0.4.1"
rand = "0.8.5"
stun_codec = "0.3.4"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "net", "time"] }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "fmt"] }
tracing-stackdriver = { version = "0.10.0", features = ["opentelemetry"] }
tracing-opentelemetry = "0.23.0"
opentelemetry = { version = "0.20.0", features = ["rt-tokio", "metrics"] }
opentelemetry_api = "0.20.0"
opentelemetry-otlp = { version = "0.16.0", features = ["metrics"]}
env_logger = "0.10.2"
tracing-core = "0.1.31"
bytes = "1.4.0"
sha2 = "0.10.8"
base64 = "0.21.7"
once_cell = "1.17.1"
proptest = { version = "1.4.0", optional = true }
test-strategy = "0.3.1"
derive_more = { version = "0.99.17", features = ["from"] }
uuid = { version = "1.7.0", features = ["v4"] }
phoenix-channel = { path = "../phoenix-channel" }
url = "2.4.1"
serde = { version = "1.0.196", features = ["derive"] }
trackable = "1.3.0"
socket2 = "0.5.5"
axum = { version = "0.7.3", default-features = false, features = ["http1", "tokio"] }
backoff = "0.4"

[dev-dependencies]
redis = { version = "0.24.0", default-features = false, features = ["tokio-comp"] }
difference = "2.0.0"

[[test]]
name = "regression"
required-features = ["proptest"]
