name: Publish Docs
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-docs:
    name: Build Docusaurus 🐲
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json
      - run: |
          cd docs/
          npm ci
          npm run build
      - name: Publish Latest Docs
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: docs/build
          target-folder: .
          clean: false
          clean-exclude: |
            *.*.*/
